# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set Image Tag
      run: |
        export DATE=$(date +%s)
        echo $DATE
      id: set_image_tag

    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{join(steps.set_image_tag.outputs.*, '')}}
      run: |
        echo $IMAGE_TAG
        docker build . --file Dockerfile --tag django-hello-world:$IMAGE_TAG

    - name: Push the Dockerimage to Dockerhub
      env:
        IMAGE_TAG: ${{join(steps.run_tests.outputs.*, '')}}
      run: docker push ${{ secrets.DOCKER_USER}}/django-hello-world:$$IMAGE_TAG